[db]
    [db.exrate]
        driver = "mysql"
        dsn    = "dbo:caecaodb@tcp(192.168.3.168:3306)/exrate?charset=utf8&parseTime=true&loc=Local"
    [db.adsb]
        driver = "mysql"
        dsn    = "dbo:caecaodb@tcp(192.168.3.169:3306)/adsb?charset=utf8&parseTime=true&loc=Local"

[globalLogConfig]
    logLevel          = "info" # info/warn/error
    infoFile          = "d:\\Temp\\info.log" # can not be empty
    warnFile          = "d:\\Temp\\warn.log" # can not be empty
    errorFile         = "d:\\Temp\\error.log" # can not be empty
    messageKey        = "msg"
    levelKey          = "level"
    timeKey           = "time"
    nameKey           = "logger"
    callerKey         = "file"
    stacktraceKey     = "stacktrace"
    maxSize           = 5 # MB
    maxAge            = 10 # Days
    maxBackups        = 10
    compress          = false
    stdOutput         = true
    openCaller        = true
    openFileAndRownum = true

